- name: "test-route"
  cache-enabled: true
  cache-timeout: "5m"
  cache-max-body-size-in-mb: 100
  upstream-url: "https://felixwiedmann.de"
  upstream-timeout: "20s"
  upstream-skip-tls: false
  priority: 3
  port: 80
  hostname: "localhost"
  middlewares:
    https-redirect-enabled: true
    https-redirect-port: 443

- name: "test-route-https"
  cache-enabled: true
  cache-timeout: "5m"
  cache-max-body-size-in-mb: 100
  upstream-url: "https://felixwiedmann.de"
  upstream-timeout: "20s"
  upstream-skip-tls: false
  priority: 3
  port: 443
  hostname: "localhost"
  middlewares:
    forward-host-header: true
    https-redirect-enabled: true
    https-redirect-port: 443