- name: "test-route"
  cache-enabled: true
  cache-timeout: "5m"
  cache-max-body-size-in-mb: 100
  upstream-url: "https://felixwiedmann.de"
  upstream-timeout: "20s"
  upstream-skip-tls: false
  priority: 3
  port: 8080
  hostname: "localhost"
- name: "test-route2"
  cache-enabled: true
  cache-timeout: "5m"
  cache-max-body-size-in-mb: 100
  upstream-url: "https://docker.com"
  upstream-timeout: "20s"
  upstream-skip-tls: false
  priority: 3
  port: 8081
  hostname: "test.localhost"
