name: Go
on: [push, pull_request]
jobs:
  test:
    name: go-test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - name: Go test with race and coverage
        run: |
          go test -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          fail_ci_if_error: true

  lint:
    name: lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31

  build:
    name: go build
    runs-on: ubuntu-18.04
    needs: [test,lint]
    steps:
      - uses: actions/checkout@v2
      - name: Init go-semantic-release
        run: |
          curl -L -o go-semantic-release.zip  https://github.com/Nightapes/go-semantic-release/releases/download/v1.4.2/go-semantic-release.linux_x86_64.zip
          unzip go-semantic-release.zip
          mv go-semantic-release.linux_x86_64 go-semantic-release
          chmod +x go-semantic-release
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - name: Go build
        run: |
          CGO_ENABLED=0 go build -o prox -ldflags "-w -s" cmd/main.go
      - name: Upload binary
        uses: actions/upload-artifact@v1
        with:
          name: go-build-binary
          path: prox
      - name: Upload binary semantic release
        uses: actions/upload-artifact@v1
        with:
          name: releaser-tool
          path: go-semantic-release

  build-docker:
    name: build docker images
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Download go-build binary
        uses: actions/download-artifact@v1
        with:
          name: go-build-binary
      - name: Download releaser binary
        uses: actions/download-artifact@v1
        with:
          name: releaser-tool
      - name: move binary to working dir
        run: mv go-build-binary/prox .
      - name: move binary to working dir
        run: mv releaser-tool/go-semantic-release . && chmod +x go-semantic-release
      - name: export version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "::set-env PROX_VERSION=$(./go-semantic-release next)"
      - name: build-docker-latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            wiedmannfelix/prox:latest
            wiedmannfelix/proxy:${{ env.PROX_VERSION }}
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./go-semantic-release release